### ISSUE TITLE
Branch naming convention 

### ISSUE THREAD

**Issue by lionellloh** [MLH-Fellowship/0.0.1-podcast-cli#12]
Just to standardise some git conventions, I am proposing the following naming convention - 

`<type-of-branch>/<feature-name>` 

For example, I have started off by pushing `feat/fetch-mp3-url` 

What do you guys think? 

@whoiswillma @bartekpacia @emctackett

**Comment by bartekpacia** [comment]
I think it's a good idea. I'll create `CONTRIBUTING.md` and add this here, among other things

**Comment by emctackett** [comment]
Sounds great.
Thanks for doing that, @bartekpacia
