### ISSUE TITLE
Fetch API -> parse into CLI options 

### ISSUE THREAD

**Issue by lionellloh** [MLH-Fellowship/0.0.1-podcast-cli#14]
This should be one of the early use cases of the user. 

After issuing a particular command, e.g. `podcast` in zsh, they should be brought to a page where they can select the podcasts. The list of podcast is populated by the API call. 

I think parsing might be a slight pain using shell scripting. I am not sure how often we should leverage on Python because it seems that we have made that decision :P

**Comment by emctackett** [comment]
I'll work on this a bit right now.  Will update the team on progress.

**Comment by lionellloh** [comment]
Feature completed in [PR 22](https://github.com/MLH-Fellowship/0.0.1-podcast-cli/pull/22)

**Comment by lionellloh** [comment]
Feature completed in[ PR 22](https://github.com/MLH-Fellowship/0.0.1-podcast-cli/pull/22)
