### ISSUE TITLE
How to play back MP3 from zsh?

### ISSUE THREAD

**Issue by whoiswillma** [MLH-Fellowship/0.0.1-podcast-cli#16]
**Goal:** be able to control playback of a mp3 file from zsh. 

I considered a few options, but please let me know if you have a better solution.

1. `ffplay`. FFmpeg has a small command line utility that plays back audio. It works seamlessly, and it has a lot of the features we want, including play/pause, jump forward and backwards in short increments. However, we can't control `ffplay` from zsh without a GUI, so this is a non-starter.

2. `mpg123`. Lots of great controls including all of the above and pitch control, playlist controls, next track, previous track, etc. `mpg123` supports local playback as well as mp3 streaming.

    Advantage: Most of the work of mp3 playback work is done
    Disadvantage: We're locked into the `mpg123` UI

![Screen Shot 2020-06-02 at 15 27 04](https://user-images.githubusercontent.com/1882991/83561265-8ab7f880-a4e5-11ea-82af-382fb2883119.png)

mpg123 also supports the following playback controls:

```
 -= terminal control keys =-
[s]     or [ ] interrupt/restart playback (i.e. '(un)pause')
[f]     next track
[d]     previous track
[b]     back to beginning of track
[p]     loop around current position (like a damaged audio CD;-)
[.]     forward
[,]     rewind
[:]     fast forward
[;]     fast rewind
[>]     fine forward
[<]     fine rewind
[+]     volume up
[-]     volume down
[r]     RVA switch
[v]     verbose switch
[l]     list current playlist, indicating current track there
[t]     display tag info (again)
[m]     print MPEG header info (again)
[h]     this help
[q]     quit
[c]     or [C] pitch up (small step, big step)
[x]     or [X] pitch down (small step, big step)
[w]     reset pitch to zero
```

3. `python-vlc`. More customization than the previous option, but more work. We'll have to use python, albeit minimally. `python-vlc` also supports local playback and streaming.

     Advantage: More customization than `mpg123`
     Disadvantage: Fewer controls built-in. For example, we'd have to implement playlists manually. It will be hacky to retrieve information such as the current playback position from the player, but it's possible.

Between `mpg123` and `python-vlc`, what are our thoughts on which option to go with?

**Comment by emctackett** [comment]
Hey William, after our call earlier, did you have any thoughts on the possibility of using the existing `vox` plugin for oh-my-zsh?  

I played around with it, and here is what I came up with:

```
Using Vox plugin to play audio: 
- Download vox app https://vox.rocks
- Follow README instructions to get vox plugin-- https://github.com/andrewbonnington/vox.plugin.zsh.
- Add podcast to your vox player and the plugin works from the command line.

So the problem domain for us would be: 
- adding podcasts (mp3 files) downloaded from `dev.to` 
to a specified collection of the user's vox player
- playing those podcasts via vox (abstracting over the existing vox plugin).
```

Lionell has a solution (though it isn't optimal just yet) for downloading the mp3 files.  Our next step could potentially be:
- automatically adding these mp3 files to a vox player's Dev.to 'collection'.

Let me know if this is an option you're open to.  I'm going to do some more research on `mpg123`.  We will also hear from @lionellloh and @bartekpacia in the morning, I'm sure.

**Comment by whoiswillma** [comment]
I'd be down to use Vox. It seems like a completely viable way forward on its own.

However, after seeing the `vox` plugin implementation, I think it's possible to make it work with `ffplay` by using the same tactic the `vox` plugin uses to control Vox. I'll experiment and get back.

**Comment by whoiswillma** [comment]
I've come to the conclusion that using `ffplay` is impractical, so I'm in full support of using `vox`.

**Comment by bartekpacia** [comment]
Won't we introduce the dependency on `vox` then? (e.g I didn't have it preinstalled)

**Comment by emctackett** [comment]
Yes, definitely.  I think it is okay as long as that is clearly documented in the README?
