### ISSUE TITLE
Change file name fetch.zsh to podcast.zsh

### ISSUE THREAD

**Issue by emctackett** [MLH-Fellowship/0.0.1-podcast-cli#17]
https://github.com/MLH-Fellowship/0.0.1-podcast-cli/pull/13#issuecomment-637918137

See the above comment from Larson.

`_fetch` is a reserved word in zsh, because of auto-correct functionality, we shouldn't use `fetch`.  `podcast` isn't a reserved word, we can use that instead.

**Comment by lionellloh** [comment]
Zsh file replaced with Python functionality.
