### ISSUE TITLE
Display Podcast Icon via ASCII art?

### ISSUE THREAD

**Issue by emctackett** [MLH-Fellowship/0.0.1-podcast-cli#8]
represent podcast icon via ascii art and display in terminal

**Comment by lionellloh** [comment]
Found a sweet package `jp2a`. You can install it with homebrew by doing `brew install jp2a`

**Comment by larson-carter** [comment]
@lionellloh 

Great find, you are in luck.

Since you don't want to make it locked to a mac, try to bundle your deps with this: https://github.com/cslarsen/jp2a

That way it should logically work on mac, linux, and windows.
